Update key_pair_w_toml.yml

diff --git a/.github/workflows/key_pair_w_toml.yml b/.github/workflows/key_pair_w_toml.yml
--- a/.github/workflows/key_pair_w_toml.yml
+++ b/.github/workflows/key_pair_w_toml.yml
@@ -17,9 +17,9 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Use Python 3.11.x
-        uses: actions/setup-python@v2.2.1
+        uses: actions/setup-python@v4
         with:
-          python-version: 3.11.x
+          python-version: 3.11
 
       - name: Decrypt RSA key
         run: |
@@ -31,7 +31,7 @@ jobs:
           cat <<EOF > .github/workflows/connections.toml
           account = "${{ secrets.SF_ACCOUNT }}"
           user = "${{ secrets.SF_USERNAME }}"
-          authenticator= "SNOWFLAKE_JWT"
+          authenticator = "SNOWFLAKE_JWT"
           role = "${{ secrets.SF_ROLE }}"
           warehouse = "${{ secrets.SF_WAREHOUSE }}"
           database = "${{ secrets.SF_DATABASE }}"
@@ -45,14 +45,17 @@ jobs:
       - name: Debug connections.toml
         run: cat .github/workflows/connections.toml
 
-
-
-
-      - name: Changing Permissions of connections.toml file
+      - name: Set permissions for connections.toml
+        run: chmod 0600 .github/workflows/connections.toml
+      - name: Confirm connections.toml exists
         run: |
-          chown $USER ".github/workflows/connections.toml"
-          chmod 0600 ".github/workflows/connections.toml"
-          
+          if [ -f .github/workflows/connections.toml ]; then
+            echo "connections.toml exists"
+          else
+            echo "connections.toml is missing"
+            exit 1
+          fi
+
       - name: Run schemachange
         run: |
           echo "Installing schemachange"
@@ -60,5 +63,6 @@ jobs:
 
           echo "Running schemachange"
           schemachange -f migrations --connections-file-path .github/workflows/connections.toml 
+
       - name: Clean up sensitive files
-        run: rm -f rsa_key.p8 connections.toml
+        run: rm -f rsa_key.p8 .github/workflows/connections.toml
